### ISSUE TITLE
支持统一身份认证登录？

### ISSUE THREAD

**Issue by padeoe** [Mygod/nju-portal-login-android#17]
对于你这么注重功能大而全的人来说，难道不支持一下统一身份账号登录校园网吗。https://github.com/padeoe/AutoConnect/blob/newUI/screenshot1.png
我还没做，你先做一个呗

**Comment by Mygod** [comment]
这个能登录吗？我试了下没成功。

**Comment by padeoe** [comment]
mm.nju.edu.cn里面有这个功能，你反编译看一下里面有api，这个api比较蠢，需要用户把自己的ip硬编码发给服务器，因此在宿舍nat路由后用不了。不过可以在教学楼用，所以你还是可以搞一下，显得app功能多。

**Comment by Mygod** [comment]
@padeoe 显得功能多和功能多是两回事……以及听起来确实没用。

Closing this issue.

**Comment by padeoe** [comment]
好吧，竟然安利失败。所以我也没有支持。我没支持的功能都是我觉得没什么用的功能

**Comment by Mygod** [comment]
@padeoe 好的吧……
