### ISSUE TITLE
Support services other than 学生标准计时服务

### ISSUE THREAD

**Issue by Mygod** [Mygod/nju-portal-login-android#6]

**Comment by padeoe** [comment]
所以服务，包括教职工标准服务，专家，校外接入二合一，免费组等都没有什么区别，唯一区别是session limit，有些服务类型session limit是大于一的。你可以在用户首次连接时检测session limit。登陆时，检测当前登陆设备数是否超出session limit。

**Comment by Mygod** [comment]
@padeoe 谢谢，那么超过并发限制时会让用户选择哪个下线？

**Comment by padeoe** [comment]
会提示用户。你可以自行处理这个过程，让用户选择哪个下线，不用管p.nju是什么样的。

**Comment by Mygod** [comment]
@padeoe 所以如何知道 session limit 即将超过或已经超过？

EDIT: 看到了谢谢。

**Comment by padeoe** [comment]
你不是做了登陆前检查其他设备是否在线吗，这个时候统计当前在线设备数量，对比是否达到了 session limit 即可啊。具体是：
1.在http://bras.nju.edu.cn:8080/manage/self/userinfo/getinfo 中获得session_limit。
2.用户点击登录
3.在http://bras.nju.edu.cn:8080/manage/self/online/getlist 进行查询当前在线用户，统计在线用户数量n。
4.比较session_limit与n的大小
5.自定义后续操作。

**Comment by Mygod** [comment]
@padeoe 我看到了而且编辑了刚才上面的那个 comment，刚才没看到 `session_limit` 在哪里。:stuck_out_tongue:

**Comment by padeoe** [comment]
话说这功能我自己还没做...自己目前没这个需求，并且懒...不过恰好看到你issue里有就说一下了。

**Comment by Mygod** [comment]
@padeoe 噗我也不是很想做！我就先看看你做了什么功能抄点过来吧哈哈哈！

**Comment by padeoe** [comment]
@Mygod 我全部功能就都写在readme里了，没啥特色功能，主要是个人够用。不过我接下来准备做一个全新的程序，适用于任意需要登录的wifi自动登录。这个你感兴趣吗...这个我申请了学校的创新项目...

**Comment by Mygod** [comment]
@padeoe 这坑太大了，我远离= =

**Comment by padeoe** [comment]
@Mygod 这个能做的...就是比较麻烦...类似于lastpass自动填写密码的原理。

**Comment by Mygod** [comment]
你指任意需要登录的 WiFi 还是任意需要登录校园网的 WiFi？

EDIT: 好吧我懂了，那你是不是还要支持动态密码和验证码……

**Comment by padeoe** [comment]
@Mygod 任意需要登录的 WiFi 。对，配合自动填写短信验证码。

**Comment by Mygod** [comment]
@padeoe 可以的，你加油。

**Comment by padeoe** [comment]
@Mygod  233大三完全没有时间做哎，跟我同一期创新项目的同学都退了项目了...将来我也有可能退掉...

**Comment by Mygod** [comment]
就因为没时间吗……

**Comment by padeoe** [comment]
@Mygod 是，马上还要卖身实习去，课都没时间上了。羡慕你大二自由身啊

**Comment by Mygod** [comment]
（然而我才大一）

**Comment by padeoe** [comment]
好吧，看来我记错了？

**Comment by Mygod** [comment]
还是决定 tag “feedback wanted”，暂时没什么需求，~~懒得~~不打算实现。

**Comment by Mygod** [comment]
@padeoe 现在好像可以同时上两个，但是 session_limit 还是 1。:confused:

**Comment by Mygod** [comment]
重新看了下，现在“学生2线程网络服务(测试)”的 session_limit 确实变成 2 了。

**Comment by Mygod** [comment]
以及看起来这俩目前功能是一样的，因此可以在一个站下查询到所有的东西。

```
http://219.219.114.171/manage/self/*
http://p.nju.edu.cn/portal_io/selfservice/*
```
